Enforce root-only runtime

diff --git a/mailuops b/mailuops
--- a/mailuops
+++ b/mailuops
@@ -4,9 +4,11 @@ set +x
 umask 077
 unset BASH_ENV ENV BASH_XTRACEFD
 export LC_ALL=C
-if [[ ${EUID:-$(id -u)} -eq 0 ]]; then
-	export PATH=/usr/sbin:/usr/bin:/sbin:/bin
+if [[ $EUID -ne 0 ]]; then
+	printf 'mailuops: error: mailuops must be run as root\n' >&2
+	exit 77
 fi
+export PATH=/usr/sbin:/usr/bin:/sbin:/bin
 
 # -----------------------------------------------------------------------------
 # Constants and mutable runtime state
